# Site wide configuration

title: Honzuki no Gekokujou Translation Project
description: Translation Project for the Honzuki no Gekokujou Japanese Webnovel
logo: # 120x120 px default image used for Twitter summary card
teaser: teaser01.jpg
locale:
url: http://jdgbolt.github.io/honzuki

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: JDGBOLT
  email: jdgbolt@gmail.com
  twitter: JDGBOLT
  google:
    ad-client: 
    ad-slot: 
    analytics: UA-65158297-1
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: honquki

# Octopress Settings

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: chapter
page_layout: article

# Format titles with titlecase?
titlecase: true

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
